
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMENT DEPENDENT ELLIPSIS NEWLINE PROPERTY TAB TYPEcode : attribute\n            | context\n            | attribute code\n            | context codeattribute : TYPE ASSIGN NEWLINEattribute : TYPEattribute : PROPERTYattribute : DEPENDENTcontext : ASSIGN NEWLINEcontext : COMMENTcontext : NEWLINEcontext : ELLIPSIScontext : TAB'
    
_lr_action_items = {'TYPE':([0,2,3,4,6,7,8,9,10,11,15,16,],[4,4,4,-6,-11,-7,-8,-10,-12,-13,-9,-5,]),'PROPERTY':([0,2,3,4,6,7,8,9,10,11,15,16,],[7,7,7,-6,-11,-7,-8,-10,-12,-13,-9,-5,]),'DEPENDENT':([0,2,3,4,6,7,8,9,10,11,15,16,],[8,8,8,-6,-11,-7,-8,-10,-12,-13,-9,-5,]),'ASSIGN':([0,2,3,4,6,7,8,9,10,11,15,16,],[5,5,5,14,-11,-7,-8,-10,-12,-13,-9,-5,]),'COMMENT':([0,2,3,4,6,7,8,9,10,11,15,16,],[9,9,9,-6,-11,-7,-8,-10,-12,-13,-9,-5,]),'NEWLINE':([0,2,3,4,5,6,7,8,9,10,11,14,15,16,],[6,6,6,-6,15,-11,-7,-8,-10,-12,-13,16,-9,-5,]),'ELLIPSIS':([0,2,3,4,6,7,8,9,10,11,15,16,],[10,10,10,-6,-11,-7,-8,-10,-12,-13,-9,-5,]),'TAB':([0,2,3,4,6,7,8,9,10,11,15,16,],[11,11,11,-6,-11,-7,-8,-10,-12,-13,-9,-5,]),'$end':([1,2,3,4,6,7,8,9,10,11,12,13,15,16,],[0,-1,-2,-6,-11,-7,-8,-10,-12,-13,-3,-4,-9,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'code':([0,2,3,],[1,12,13,]),'attribute':([0,2,3,],[2,2,2,]),'context':([0,2,3,],[3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> code","S'",1,None,None,None),
  ('code -> attribute','code',1,'p_attributes','main.py',51),
  ('code -> context','code',1,'p_attributes','main.py',52),
  ('code -> attribute code','code',2,'p_attributes','main.py',53),
  ('code -> context code','code',2,'p_attributes','main.py',54),
  ('attribute -> TYPE ASSIGN NEWLINE','attribute',3,'p_attribute_type_assign_newline','main.py',56),
  ('attribute -> TYPE','attribute',1,'p_attribute_type','main.py',64),
  ('attribute -> PROPERTY','attribute',1,'p_attribute_property','main.py',72),
  ('attribute -> DEPENDENT','attribute',1,'p_attribute_dependent','main.py',75),
  ('context -> ASSIGN NEWLINE','context',2,'p_attribute_assignment','main.py',78),
  ('context -> COMMENT','context',1,'p_attribute_comment','main.py',82),
  ('context -> NEWLINE','context',1,'p_attribute_newline','main.py',85),
  ('context -> ELLIPSIS','context',1,'p_attribute_ELLIPSIS','main.py',89),
  ('context -> TAB','context',1,'p_attribute_tab','main.py',92),
]
